USE UNIVER
SELECT FACULTY.FACULTY_NAME, GROUPS.PROFESSION, PROGRESS.SUBJECT, 
    ROUND(AVG(CAST(PROGRESS.NOTE AS FLOAT)), 2) AS AVG_GRADE
FROM FACULTY
INNER JOIN GROUPS ON FACULTY.FACULTY = GROUPS.FACULTY
INNER JOIN STUDENT ON GROUPS.IDGROUP = STUDENT.IDGROUP
INNER JOIN PROGRESS ON STUDENT.IDSTUDENT = PROGRESS.IDSTUDENT
GROUP BY FACULTY.FACULTY_NAME, GROUPS.PROFESSION, PROGRESS.SUBJECT
ORDER BY AVG_GRADE DESC;
