USE UNIVER
SELECT a.AUDITORIUM_TYPE AS AUDIENCE_TYPE,
       COUNT(*) AS TOTAL_AUDITORIUMS,
       MIN(a.AUDITORIUM_CAPACITY) AS MIN_CAPACITY,
       MAX(a.AUDITORIUM_CAPACITY) AS MAX_CAPACITY,
       AVG(a.AUDITORIUM_CAPACITY) AS AVG_CAPACITY,
       SUM(a.AUDITORIUM_CAPACITY) AS TOTAL_CAPACITY
FROM AUDITORIUM a
INNER JOIN AUDITORIUM_TYPE at ON a.AUDITORIUM_TYPE = at.AUDITORIUM_TYPE
GROUP BY a.AUDITORIUM_TYPE;
