USE UNIVER
SELECT 
  FACULTY.FACULTY_NAME, 
  GROUPS.PROFESSION, 
  GROUPS.YEAR_FIRST, 
  PROGRESS.SUBJECT, 
  ROUND(AVG(CAST(PROGRESS.NOTE AS FLOAT)), 2) AS AVERAGE_GRADE
FROM 
  FACULTY 
  JOIN GROUPS ON FACULTY.FACULTY = GROUPS.FACULTY 
  JOIN STUDENT ON GROUPS.IDGROUP = STUDENT.IDGROUP 
  JOIN PROGRESS ON STUDENT.IDSTUDENT = PROGRESS.IDSTUDENT 
WHERE 
  PROGRESS.SUBJECT IN ('¡ƒ', 'Œ¿Ëœ')
GROUP BY 
  FACULTY.FACULTY_NAME, 
  GROUPS.PROFESSION, 
  GROUPS.YEAR_FIRST, 
  PROGRESS.SUBJECT 
ORDER BY 
  AVERAGE_GRADE DESC;
