use UNIVER
SELECT GROUPS.PROFESSION AS SPECIALTY, PROGRESS.SUBJECT AS DISCIPLINE, ROUND(AVG(PROGRESS.NOTE), 2) AS AVG_GRADE
FROM FACULTY
INNER JOIN GROUPS ON FACULTY.FACULTY = GROUPS.FACULTY
INNER JOIN STUDENT ON GROUPS.IDGROUP = STUDENT.IDGROUP
INNER JOIN PROGRESS ON STUDENT.IDSTUDENT = PROGRESS.IDSTUDENT
WHERE FACULTY.FACULTY_NAME = 'Технология органических веществ'
GROUP BY GROUPS.PROFESSION, PROGRESS.SUBJECT;
